version: 2

formats:
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    build:
      pdf:
        - echo "building pdf $READTHEDOCS_OUTPUT"
        - mkdir -p $READTHEDOCS_OUTPUT/pdf
        - cp docs/github_modeldescription.tex $READTHEDOCS_OUTPUT/pdf/
          #- cd _readthedocs/pdf
        - echo "$PWD"
        - pdflatex -interaction=nonstopmode -recorder --jobname="microcircuit-pd14-model"  "$READTHEDOCS_OUTPUT/pdf/github_modeldescription.tex"
        - pdflatex -interaction=nonstopmode -recorder --jobname="microcircuit-pd14-model"  "$READTHEDOCS_OUTPUT/pdf/github_modeldescription.tex"
        - cp $READTHEDOCS_OUTPUT/microcircuit-pd14-model.pdf $READTHEDOCS_OUTPUT/html/_static/
        - ls _readthedocs/html/_static
sphinx:
  builder: html
  configuration: docs/conf.py

python:
   install:
     - method: pip
       path: PyNEST/
       extra_requirements:
         - doc


