version: 2

formats:
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    build:
      pdf:
        - echo "building pdf $READTHEDOCS_OUTPUT"
        - mkdir -p $READTHEDOCS_OUTPUT/pdf
        - cp docs/github_modeldescription.tex $READTHEDOCS_OUTPUT/pdf/
        - cd _readthedocs/pdf
        - ls  #
        - echo "$PWD"
        - pdflatex -interaction=nonstopmode -recorder --jobname="microcircuit-pd14-model"  "github_modeldescription.tex"
          #- latex docs/github_modeldescription.tex -output-format='pdf' -output-directory=$READTHEDOCS_OUTPUT/pdf/ #- echo "hello world" > $READTHEDOCS_OUTPUT/pdf/index.pdf
          #- latex docs/github_modeldescription.tex -output-format='pdf' -output-directory=$READTHEDOCS_OUTPUT/pdf/ #- echo "hello world" > $READTHEDOCS_OUTPUT/pdf/index.pdf
        - ls $READTHEDOCS_OUTPUT/pdf
sphinx:
  builder: html
  configuration: docs/conf.py

python:
   install:
     - method: pip
       path: PyNEST/
       extra_requirements:
         - doc


