version: 2

formats:
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    build:
      pdf:
        - echo "building pdf $READTHEDOCS_OUTPUT"
        - cp ./gihtub_modeldescription.tex $READTHEDOCS_OUTPUT/pdf/
        - make latexpdf  #- echo "hello world" > $READTHEDOCS_OUTPUT/pdf/index.pdf
sphinx:
  builder: html
  configuration: docs/conf.py

python:
   install:
     - method: pip
       path: PyNEST/
       extra_requirements:
         - doc


