version: 2

formats:
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    build:
      pdf:
        - echo "building pdf $READTHEDOCS_OUTPUT"
        - ls docs/
        - mkdir -p $READTHEDOCS_OUTPUT/pdf
          #- cp docs/github_modeldescription.tex $READTHEDOCS_OUTPUT/pdf/
          #
        - latex docs/github_modeldescription.tex  -output-directory=$READTHEDOCS_OUTPUT/pdf/ #- echo "hello world" > $READTHEDOCS_OUTPUT/pdf/index.pdf
sphinx:
  builder: html
  configuration: docs/conf.py

python:
   install:
     - method: pip
       path: PyNEST/
       extra_requirements:
         - doc


